import UIKit

extension UIColor {

    class func msr_materialRed50() -> UIColor { return %+0xfde0dc }
    class func msr_materialRed100() -> UIColor { return %+0xf9bdbb }
    class func msr_materialRed200() -> UIColor { return %+0xf69988 }
    class func msr_materialRed300() -> UIColor { return %+0xf36c60 }
    class func msr_materialRed400() -> UIColor { return %+0xe84e40 }
    class func msr_materialRed500() -> UIColor { return %+0xe51c23 }
    class func msr_materialRed600() -> UIColor { return %+0xdd191d }
    class func msr_materialRed700() -> UIColor { return %+0xd01716 }
    class func msr_materialRed800() -> UIColor { return %+0xc41411 }
    class func msr_materialRed900() -> UIColor { return %+0xb0120a }
    class func msr_materialRedA100() -> UIColor { return %+0xff7997 }
    class func msr_materialRedA200() -> UIColor { return %+0xff5177 }
    class func msr_materialRedA400() -> UIColor { return %+0xff2d6f }
    class func msr_materialRedA700() -> UIColor { return %+0xe00032 }
    class func msr_materialRed() -> UIColor { return msr_materialRed500() }

    class func msr_materialPink50() -> UIColor { return %+0xfce4ec }
    class func msr_materialPink100() -> UIColor { return %+0xf8bbd0 }
    class func msr_materialPink200() -> UIColor { return %+0xf48fb1 }
    class func msr_materialPink300() -> UIColor { return %+0xf06292 }
    class func msr_materialPink400() -> UIColor { return %+0xec407a }
    class func msr_materialPink500() -> UIColor { return %+0xe91e63 }
    class func msr_materialPink600() -> UIColor { return %+0xd81b60 }
    class func msr_materialPink700() -> UIColor { return %+0xc2185b }
    class func msr_materialPink800() -> UIColor { return %+0xad1457 }
    class func msr_materialPink900() -> UIColor { return %+0x880e4f }
    class func msr_materialPinkA100() -> UIColor { return %+0xff80ab }
    class func msr_materialPinkA200() -> UIColor { return %+0xff4081 }
    class func msr_materialPinkA400() -> UIColor { return %+0xf50057 }
    class func msr_materialPinkA700() -> UIColor { return %+0xc51162 }
    class func msr_materialPink() -> UIColor { return msr_materialPink500() }

    class func msr_materialPurple50() -> UIColor { return %+0xf3e5f5 }
    class func msr_materialPurple100() -> UIColor { return %+0xe1bee7 }
    class func msr_materialPurple200() -> UIColor { return %+0xce93d8 }
    class func msr_materialPurple300() -> UIColor { return %+0xba68c8 }
    class func msr_materialPurple400() -> UIColor { return %+0xab47bc }
    class func msr_materialPurple500() -> UIColor { return %+0x9c27b0 }
    class func msr_materialPurple600() -> UIColor { return %+0x8e24aa }
    class func msr_materialPurple700() -> UIColor { return %+0x7b1fa2 }
    class func msr_materialPurple800() -> UIColor { return %+0x6a1b9a }
    class func msr_materialPurple900() -> UIColor { return %+0x4a148c }
    class func msr_materialPurpleA100() -> UIColor { return %+0xea80fc }
    class func msr_materialPurpleA200() -> UIColor { return %+0xe040fb }
    class func msr_materialPurpleA400() -> UIColor { return %+0xd500f9 }
    class func msr_materialPurpleA700() -> UIColor { return %+0xaa00ff }
    class func msr_materialPurple() -> UIColor { return msr_materialPurple500() }

    class func msr_materialDeepPurple50() -> UIColor { return %+0xede7f6 }
    class func msr_materialDeepPurple100() -> UIColor { return %+0xd1c4e9 }
    class func msr_materialDeepPurple200() -> UIColor { return %+0xb39ddb }
    class func msr_materialDeepPurple300() -> UIColor { return %+0x9575cd }
    class func msr_materialDeepPurple400() -> UIColor { return %+0x7e57c2 }
    class func msr_materialDeepPurple500() -> UIColor { return %+0x673ab7 }
    class func msr_materialDeepPurple600() -> UIColor { return %+0x5e35b1 }
    class func msr_materialDeepPurple700() -> UIColor { return %+0x512da8 }
    class func msr_materialDeepPurple800() -> UIColor { return %+0x4527a0 }
    class func msr_materialDeepPurple900() -> UIColor { return %+0x311b92 }
    class func msr_materialDeepPurpleA100() -> UIColor { return %+0xb388ff }
    class func msr_materialDeepPurpleA200() -> UIColor { return %+0x7c4dff }
    class func msr_materialDeepPurpleA400() -> UIColor { return %+0x651fff }
    class func msr_materialDeepPurpleA700() -> UIColor { return %+0x6200ea }
    class func msr_materialDeepPurple() -> UIColor { return msr_materialDeepPurple500() }

    class func msr_materialIndigo50() -> UIColor { return %+0xe8eaf6 }
    class func msr_materialIndigo100() -> UIColor { return %+0xc5cae9 }
    class func msr_materialIndigo200() -> UIColor { return %+0x9fa8da }
    class func msr_materialIndigo300() -> UIColor { return %+0x7986cb }
    class func msr_materialIndigo400() -> UIColor { return %+0x5c6bc0 }
    class func msr_materialIndigo500() -> UIColor { return %+0x3f51b5 }
    class func msr_materialIndigo600() -> UIColor { return %+0x3949ab }
    class func msr_materialIndigo700() -> UIColor { return %+0x303f9f }
    class func msr_materialIndigo800() -> UIColor { return %+0x283593 }
    class func msr_materialIndigo900() -> UIColor { return %+0x1a237e }
    class func msr_materialIndigoA100() -> UIColor { return %+0x8c9eff }
    class func msr_materialIndigoA200() -> UIColor { return %+0x536dfe }
    class func msr_materialIndigoA400() -> UIColor { return %+0x3d5afe }
    class func msr_materialIndigoA700() -> UIColor { return %+0x304ffe }
    class func msr_materialIndigo() -> UIColor { return msr_materialIndigo500() }

    class func msr_materialBlue50() -> UIColor { return %+0xe7e9fd }
    class func msr_materialBlue100() -> UIColor { return %+0xd0d9ff }
    class func msr_materialBlue200() -> UIColor { return %+0xafbfff }
    class func msr_materialBlue300() -> UIColor { return %+0x91a7ff }
    class func msr_materialBlue400() -> UIColor { return %+0x738ffe }
    class func msr_materialBlue500() -> UIColor { return %+0x5677fc }
    class func msr_materialBlue600() -> UIColor { return %+0x4e6cef }
    class func msr_materialBlue700() -> UIColor { return %+0x455ede }
    class func msr_materialBlue800() -> UIColor { return %+0x3b50ce }
    class func msr_materialBlue900() -> UIColor { return %+0x2a36b1 }
    class func msr_materialBlueA100() -> UIColor { return %+0xa6baff }
    class func msr_materialBlueA200() -> UIColor { return %+0x6889ff }
    class func msr_materialBlueA400() -> UIColor { return %+0x4d73ff }
    class func msr_materialBlueA700() -> UIColor { return %+0x4d69ff }
    class func msr_materialBlue() -> UIColor { return msr_materialBlue500() }

    class func msr_materialLightBlue50() -> UIColor { return %+0xe1f5fe }
    class func msr_materialLightBlue100() -> UIColor { return %+0xb3e5fc }
    class func msr_materialLightBlue200() -> UIColor { return %+0x81d4fa }
    class func msr_materialLightBlue300() -> UIColor { return %+0x4fc3f7 }
    class func msr_materialLightBlue400() -> UIColor { return %+0x29b6f6 }
    class func msr_materialLightBlue500() -> UIColor { return %+0x03a9f4 }
    class func msr_materialLightBlue600() -> UIColor { return %+0x039be5 }
    class func msr_materialLightBlue700() -> UIColor { return %+0x0288d1 }
    class func msr_materialLightBlue800() -> UIColor { return %+0x0277bd }
    class func msr_materialLightBlue900() -> UIColor { return %+0x01579b }
    class func msr_materialLightBlueA100() -> UIColor { return %+0x80d8ff }
    class func msr_materialLightBlueA200() -> UIColor { return %+0x40c4ff }
    class func msr_materialLightBlueA400() -> UIColor { return %+0x00b0ff }
    class func msr_materialLightBlueA700() -> UIColor { return %+0x0091ea }
    class func msr_materialLightBlue() -> UIColor { return msr_materialLightBlue500() }

    class func msr_materialCyan50() -> UIColor { return %+0xe0f7fa }
    class func msr_materialCyan100() -> UIColor { return %+0xb2ebf2 }
    class func msr_materialCyan200() -> UIColor { return %+0x80deea }
    class func msr_materialCyan300() -> UIColor { return %+0x4dd0e1 }
    class func msr_materialCyan400() -> UIColor { return %+0x26c6da }
    class func msr_materialCyan500() -> UIColor { return %+0x00bcd4 }
    class func msr_materialCyan600() -> UIColor { return %+0x00acc1 }
    class func msr_materialCyan700() -> UIColor { return %+0x0097a7 }
    class func msr_materialCyan800() -> UIColor { return %+0x00838f }
    class func msr_materialCyan900() -> UIColor { return %+0x006064 }
    class func msr_materialCyanA100() -> UIColor { return %+0x84ffff }
    class func msr_materialCyanA200() -> UIColor { return %+0x18ffff }
    class func msr_materialCyanA400() -> UIColor { return %+0x00e5ff }
    class func msr_materialCyanA700() -> UIColor { return %+0x00b8d4 }
    class func msr_materialCyan() -> UIColor { return msr_materialCyan500() }

    class func msr_materialTeal50() -> UIColor { return %+0xe0f2f1 }
    class func msr_materialTeal100() -> UIColor { return %+0xb2dfdb }
    class func msr_materialTeal200() -> UIColor { return %+0x80cbc4 }
    class func msr_materialTeal300() -> UIColor { return %+0x4db6ac }
    class func msr_materialTeal400() -> UIColor { return %+0x26a69a }
    class func msr_materialTeal500() -> UIColor { return %+0x009688 }
    class func msr_materialTeal600() -> UIColor { return %+0x00897b }
    class func msr_materialTeal700() -> UIColor { return %+0x00796b }
    class func msr_materialTeal800() -> UIColor { return %+0x00695c }
    class func msr_materialTeal900() -> UIColor { return %+0x004d40 }
    class func msr_materialTealA100() -> UIColor { return %+0xa7ffeb }
    class func msr_materialTealA200() -> UIColor { return %+0x64ffda }
    class func msr_materialTealA400() -> UIColor { return %+0x1de9b6 }
    class func msr_materialTealA700() -> UIColor { return %+0x00bfa5 }
    class func msr_materialTeal() -> UIColor { return msr_materialTeal500() }

    class func msr_materialGreen50() -> UIColor { return %+0xd0f8ce }
    class func msr_materialGreen100() -> UIColor { return %+0xa3e9a4 }
    class func msr_materialGreen200() -> UIColor { return %+0x72d572 }
    class func msr_materialGreen300() -> UIColor { return %+0x42bd41 }
    class func msr_materialGreen400() -> UIColor { return %+0x2baf2b }
    class func msr_materialGreen500() -> UIColor { return %+0x259b24 }
    class func msr_materialGreen600() -> UIColor { return %+0x0a8f08 }
    class func msr_materialGreen700() -> UIColor { return %+0x0a7e07 }
    class func msr_materialGreen800() -> UIColor { return %+0x056f00 }
    class func msr_materialGreen900() -> UIColor { return %+0x0d5302 }
    class func msr_materialGreenA100() -> UIColor { return %+0xa2f78d }
    class func msr_materialGreenA200() -> UIColor { return %+0x5af158 }
    class func msr_materialGreenA400() -> UIColor { return %+0x14e715 }
    class func msr_materialGreenA700() -> UIColor { return %+0x12c700 }
    class func msr_materialGreen() -> UIColor { return msr_materialGreen500() }

    class func msr_materialLightGreen50() -> UIColor { return %+0xf1f8e9 }
    class func msr_materialLightGreen100() -> UIColor { return %+0xdcedc8 }
    class func msr_materialLightGreen200() -> UIColor { return %+0xc5e1a5 }
    class func msr_materialLightGreen300() -> UIColor { return %+0xaed581 }
    class func msr_materialLightGreen400() -> UIColor { return %+0x9ccc65 }
    class func msr_materialLightGreen500() -> UIColor { return %+0x8bc34a }
    class func msr_materialLightGreen600() -> UIColor { return %+0x7cb342 }
    class func msr_materialLightGreen700() -> UIColor { return %+0x689f38 }
    class func msr_materialLightGreen800() -> UIColor { return %+0x558b2f }
    class func msr_materialLightGreen900() -> UIColor { return %+0x33691e }
    class func msr_materialLightGreenA100() -> UIColor { return %+0xccff90 }
    class func msr_materialLightGreenA200() -> UIColor { return %+0xb2ff59 }
    class func msr_materialLightGreenA400() -> UIColor { return %+0x76ff03 }
    class func msr_materialLightGreenA700() -> UIColor { return %+0x64dd17 }
    class func msr_materialLightGreen() -> UIColor { return msr_materialLightGreen500() }

    class func msr_materialLime50() -> UIColor { return %+0xf9fbe7 }
    class func msr_materialLime100() -> UIColor { return %+0xf0f4c3 }
    class func msr_materialLime200() -> UIColor { return %+0xe6ee9c }
    class func msr_materialLime300() -> UIColor { return %+0xdce775 }
    class func msr_materialLime400() -> UIColor { return %+0xd4e157 }
    class func msr_materialLime500() -> UIColor { return %+0xcddc39 }
    class func msr_materialLime600() -> UIColor { return %+0xc0ca33 }
    class func msr_materialLime700() -> UIColor { return %+0xafb42b }
    class func msr_materialLime800() -> UIColor { return %+0x9e9d24 }
    class func msr_materialLime900() -> UIColor { return %+0x827717 }
    class func msr_materialLimeA100() -> UIColor { return %+0xf4ff81 }
    class func msr_materialLimeA200() -> UIColor { return %+0xeeff41 }
    class func msr_materialLimeA400() -> UIColor { return %+0xc6ff00 }
    class func msr_materialLimeA700() -> UIColor { return %+0xaeea00 }
    class func msr_materialLime() -> UIColor { return msr_materialLime500() }

    class func msr_materialYellow50() -> UIColor { return %+0xfffde7 }
    class func msr_materialYellow100() -> UIColor { return %+0xfff9c4 }
    class func msr_materialYellow200() -> UIColor { return %+0xfff59d }
    class func msr_materialYellow300() -> UIColor { return %+0xfff176 }
    class func msr_materialYellow400() -> UIColor { return %+0xffee58 }
    class func msr_materialYellow500() -> UIColor { return %+0xffeb3b }
    class func msr_materialYellow600() -> UIColor { return %+0xfdd835 }
    class func msr_materialYellow700() -> UIColor { return %+0xfbc02d }
    class func msr_materialYellow800() -> UIColor { return %+0xf9a825 }
    class func msr_materialYellow900() -> UIColor { return %+0xf57f17 }
    class func msr_materialYellowA100() -> UIColor { return %+0xffff8d }
    class func msr_materialYellowA200() -> UIColor { return %+0xffff00 }
    class func msr_materialYellowA400() -> UIColor { return %+0xffea00 }
    class func msr_materialYellowA700() -> UIColor { return %+0xffd600 }
    class func msr_materialYellow() -> UIColor { return msr_materialYellow500() }

    class func msr_materialAmber50() -> UIColor { return %+0xfff8e1 }
    class func msr_materialAmber100() -> UIColor { return %+0xffecb3 }
    class func msr_materialAmber200() -> UIColor { return %+0xffe082 }
    class func msr_materialAmber300() -> UIColor { return %+0xffd54f }
    class func msr_materialAmber400() -> UIColor { return %+0xffca28 }
    class func msr_materialAmber500() -> UIColor { return %+0xffc107 }
    class func msr_materialAmber600() -> UIColor { return %+0xffb300 }
    class func msr_materialAmber700() -> UIColor { return %+0xffa000 }
    class func msr_materialAmber800() -> UIColor { return %+0xff8f00 }
    class func msr_materialAmber900() -> UIColor { return %+0xff6f00 }
    class func msr_materialAmberA100() -> UIColor { return %+0xffe57f }
    class func msr_materialAmberA200() -> UIColor { return %+0xffd740 }
    class func msr_materialAmberA400() -> UIColor { return %+0xffc400 }
    class func msr_materialAmberA700() -> UIColor { return %+0xffab00 }
    class func msr_materialAmber() -> UIColor { return msr_materialAmber500() }

    class func msr_materialOrange50() -> UIColor { return %+0xfff3e0 }
    class func msr_materialOrange100() -> UIColor { return %+0xffe0b2 }
    class func msr_materialOrange200() -> UIColor { return %+0xffcc80 }
    class func msr_materialOrange300() -> UIColor { return %+0xffb74d }
    class func msr_materialOrange400() -> UIColor { return %+0xffa726 }
    class func msr_materialOrange500() -> UIColor { return %+0xff9800 }
    class func msr_materialOrange600() -> UIColor { return %+0xfb8c00 }
    class func msr_materialOrange700() -> UIColor { return %+0xf57c00 }
    class func msr_materialOrange800() -> UIColor { return %+0xef6c00 }
    class func msr_materialOrange900() -> UIColor { return %+0xe65100 }
    class func msr_materialOrangeA100() -> UIColor { return %+0xffd180 }
    class func msr_materialOrangeA200() -> UIColor { return %+0xffab40 }
    class func msr_materialOrangeA400() -> UIColor { return %+0xff9100 }
    class func msr_materialOrangeA700() -> UIColor { return %+0xff6d00 }
    class func msr_materialOrange() -> UIColor { return msr_materialOrange500() }

    class func msr_materialDeepOrange50() -> UIColor { return %+0xfbe9e7 }
    class func msr_materialDeepOrange100() -> UIColor { return %+0xffccbc }
    class func msr_materialDeepOrange200() -> UIColor { return %+0xffab91 }
    class func msr_materialDeepOrange300() -> UIColor { return %+0xff8a65 }
    class func msr_materialDeepOrange400() -> UIColor { return %+0xff7043 }
    class func msr_materialDeepOrange500() -> UIColor { return %+0xff5722 }
    class func msr_materialDeepOrange600() -> UIColor { return %+0xf4511e }
    class func msr_materialDeepOrange700() -> UIColor { return %+0xe64a19 }
    class func msr_materialDeepOrange800() -> UIColor { return %+0xd84315 }
    class func msr_materialDeepOrange900() -> UIColor { return %+0xbf360c }
    class func msr_materialDeepOrangeA100() -> UIColor { return %+0xff9e80 }
    class func msr_materialDeepOrangeA200() -> UIColor { return %+0xff6e40 }
    class func msr_materialDeepOrangeA400() -> UIColor { return %+0xff3d00 }
    class func msr_materialDeepOrangeA700() -> UIColor { return %+0xdd2c00 }
    class func msr_materialDeepOrange() -> UIColor { return msr_materialDeepOrange500() }

    class func msr_materialBrown50() -> UIColor { return %+0xefebe9 }
    class func msr_materialBrown100() -> UIColor { return %+0xd7ccc8 }
    class func msr_materialBrown200() -> UIColor { return %+0xbcaaa4 }
    class func msr_materialBrown300() -> UIColor { return %+0xa1887f }
    class func msr_materialBrown400() -> UIColor { return %+0x8d6e63 }
    class func msr_materialBrown500() -> UIColor { return %+0x795548 }
    class func msr_materialBrown600() -> UIColor { return %+0x6d4c41 }
    class func msr_materialBrown700() -> UIColor { return %+0x5d4037 }
    class func msr_materialBrown800() -> UIColor { return %+0x4e342e }
    class func msr_materialBrown900() -> UIColor { return %+0x3e2723 }
    class func msr_materialBrown() -> UIColor { return msr_materialBrown500() }

    class func msr_materialGray50() -> UIColor { return %+0xfafafa }
    class func msr_materialGray100() -> UIColor { return %+0xf5f5f5 }
    class func msr_materialGray200() -> UIColor { return %+0xeeeeee }
    class func msr_materialGray300() -> UIColor { return %+0xe0e0e0 }
    class func msr_materialGray400() -> UIColor { return %+0xbdbdbd }
    class func msr_materialGray500() -> UIColor { return %+0x9e9e9e }
    class func msr_materialGray600() -> UIColor { return %+0x757575 }
    class func msr_materialGray700() -> UIColor { return %+0x616161 }
    class func msr_materialGray800() -> UIColor { return %+0x424242 }
    class func msr_materialGray900() -> UIColor { return %+0x212121 }
    class func msr_materialGray() -> UIColor { return msr_materialGray500() }

    class func msr_materialBlueGray50() -> UIColor { return %+0xeceff1 }
    class func msr_materialBlueGray100() -> UIColor { return %+0xcfd8dc }
    class func msr_materialBlueGray200() -> UIColor { return %+0xb0bec5 }
    class func msr_materialBlueGray300() -> UIColor { return %+0x90a4ae }
    class func msr_materialBlueGray400() -> UIColor { return %+0x78909c }
    class func msr_materialBlueGray500() -> UIColor { return %+0x607d8b }
    class func msr_materialBlueGray600() -> UIColor { return %+0x546e7a }
    class func msr_materialBlueGray700() -> UIColor { return %+0x455a64 }
    class func msr_materialBlueGray800() -> UIColor { return %+0x37474f }
    class func msr_materialBlueGray900() -> UIColor { return %+0x263238 }
    class func msr_materialBlueGray() -> UIColor { return msr_materialBlueGray500() }

}