import UIKit

extension UIColor {

    class func materialRed50() -> UIColor { return %+0xfde0dc }
    class func materialRed100() -> UIColor { return %+0xf9bdbb }
    class func materialRed200() -> UIColor { return %+0xf69988 }
    class func materialRed300() -> UIColor { return %+0xf36c60 }
    class func materialRed400() -> UIColor { return %+0xe84e40 }
    class func materialRed500() -> UIColor { return %+0xe51c23 }
    class func materialRed600() -> UIColor { return %+0xdd191d }
    class func materialRed700() -> UIColor { return %+0xd01716 }
    class func materialRed800() -> UIColor { return %+0xc41411 }
    class func materialRed900() -> UIColor { return %+0xb0120a }
    class func materialRedA100() -> UIColor { return %+0xff7997 }
    class func materialRedA200() -> UIColor { return %+0xff5177 }
    class func materialRedA400() -> UIColor { return %+0xff2d6f }
    class func materialRedA700() -> UIColor { return %+0xe00032 }
    class func materialRed() -> UIColor { return materialRed500() }

    class func materialPink50() -> UIColor { return %+0xfce4ec }
    class func materialPink100() -> UIColor { return %+0xf8bbd0 }
    class func materialPink200() -> UIColor { return %+0xf48fb1 }
    class func materialPink300() -> UIColor { return %+0xf06292 }
    class func materialPink400() -> UIColor { return %+0xec407a }
    class func materialPink500() -> UIColor { return %+0xe91e63 }
    class func materialPink600() -> UIColor { return %+0xd81b60 }
    class func materialPink700() -> UIColor { return %+0xc2185b }
    class func materialPink800() -> UIColor { return %+0xad1457 }
    class func materialPink900() -> UIColor { return %+0x880e4f }
    class func materialPinkA100() -> UIColor { return %+0xff80ab }
    class func materialPinkA200() -> UIColor { return %+0xff4081 }
    class func materialPinkA400() -> UIColor { return %+0xf50057 }
    class func materialPinkA700() -> UIColor { return %+0xc51162 }
    class func materialPink() -> UIColor { return materialPink500() }

    class func materialPurple50() -> UIColor { return %+0xf3e5f5 }
    class func materialPurple100() -> UIColor { return %+0xe1bee7 }
    class func materialPurple200() -> UIColor { return %+0xce93d8 }
    class func materialPurple300() -> UIColor { return %+0xba68c8 }
    class func materialPurple400() -> UIColor { return %+0xab47bc }
    class func materialPurple500() -> UIColor { return %+0x9c27b0 }
    class func materialPurple600() -> UIColor { return %+0x8e24aa }
    class func materialPurple700() -> UIColor { return %+0x7b1fa2 }
    class func materialPurple800() -> UIColor { return %+0x6a1b9a }
    class func materialPurple900() -> UIColor { return %+0x4a148c }
    class func materialPurpleA100() -> UIColor { return %+0xea80fc }
    class func materialPurpleA200() -> UIColor { return %+0xe040fb }
    class func materialPurpleA400() -> UIColor { return %+0xd500f9 }
    class func materialPurpleA700() -> UIColor { return %+0xaa00ff }
    class func materialPurple() -> UIColor { return materialPurple500() }

    class func materialDeepPurple50() -> UIColor { return %+0xede7f6 }
    class func materialDeepPurple100() -> UIColor { return %+0xd1c4e9 }
    class func materialDeepPurple200() -> UIColor { return %+0xb39ddb }
    class func materialDeepPurple300() -> UIColor { return %+0x9575cd }
    class func materialDeepPurple400() -> UIColor { return %+0x7e57c2 }
    class func materialDeepPurple500() -> UIColor { return %+0x673ab7 }
    class func materialDeepPurple600() -> UIColor { return %+0x5e35b1 }
    class func materialDeepPurple700() -> UIColor { return %+0x512da8 }
    class func materialDeepPurple800() -> UIColor { return %+0x4527a0 }
    class func materialDeepPurple900() -> UIColor { return %+0x311b92 }
    class func materialDeepPurpleA100() -> UIColor { return %+0xb388ff }
    class func materialDeepPurpleA200() -> UIColor { return %+0x7c4dff }
    class func materialDeepPurpleA400() -> UIColor { return %+0x651fff }
    class func materialDeepPurpleA700() -> UIColor { return %+0x6200ea }
    class func materialDeepPurple() -> UIColor { return materialDeepPurple500() }

    class func materialIndigo50() -> UIColor { return %+0xe8eaf6 }
    class func materialIndigo100() -> UIColor { return %+0xc5cae9 }
    class func materialIndigo200() -> UIColor { return %+0x9fa8da }
    class func materialIndigo300() -> UIColor { return %+0x7986cb }
    class func materialIndigo400() -> UIColor { return %+0x5c6bc0 }
    class func materialIndigo500() -> UIColor { return %+0x3f51b5 }
    class func materialIndigo600() -> UIColor { return %+0x3949ab }
    class func materialIndigo700() -> UIColor { return %+0x303f9f }
    class func materialIndigo800() -> UIColor { return %+0x283593 }
    class func materialIndigo900() -> UIColor { return %+0x1a237e }
    class func materialIndigoA100() -> UIColor { return %+0x8c9eff }
    class func materialIndigoA200() -> UIColor { return %+0x536dfe }
    class func materialIndigoA400() -> UIColor { return %+0x3d5afe }
    class func materialIndigoA700() -> UIColor { return %+0x304ffe }
    class func materialIndigo() -> UIColor { return materialIndigo500() }

    class func materialBlue50() -> UIColor { return %+0xe7e9fd }
    class func materialBlue100() -> UIColor { return %+0xd0d9ff }
    class func materialBlue200() -> UIColor { return %+0xafbfff }
    class func materialBlue300() -> UIColor { return %+0x91a7ff }
    class func materialBlue400() -> UIColor { return %+0x738ffe }
    class func materialBlue500() -> UIColor { return %+0x5677fc }
    class func materialBlue600() -> UIColor { return %+0x4e6cef }
    class func materialBlue700() -> UIColor { return %+0x455ede }
    class func materialBlue800() -> UIColor { return %+0x3b50ce }
    class func materialBlue900() -> UIColor { return %+0x2a36b1 }
    class func materialBlueA100() -> UIColor { return %+0xa6baff }
    class func materialBlueA200() -> UIColor { return %+0x6889ff }
    class func materialBlueA400() -> UIColor { return %+0x4d73ff }
    class func materialBlueA700() -> UIColor { return %+0x4d69ff }
    class func materialBlue() -> UIColor { return materialBlue500() }

    class func materialLightBlue50() -> UIColor { return %+0xe1f5fe }
    class func materialLightBlue100() -> UIColor { return %+0xb3e5fc }
    class func materialLightBlue200() -> UIColor { return %+0x81d4fa }
    class func materialLightBlue300() -> UIColor { return %+0x4fc3f7 }
    class func materialLightBlue400() -> UIColor { return %+0x29b6f6 }
    class func materialLightBlue500() -> UIColor { return %+0x03a9f4 }
    class func materialLightBlue600() -> UIColor { return %+0x039be5 }
    class func materialLightBlue700() -> UIColor { return %+0x0288d1 }
    class func materialLightBlue800() -> UIColor { return %+0x0277bd }
    class func materialLightBlue900() -> UIColor { return %+0x01579b }
    class func materialLightBlueA100() -> UIColor { return %+0x80d8ff }
    class func materialLightBlueA200() -> UIColor { return %+0x40c4ff }
    class func materialLightBlueA400() -> UIColor { return %+0x00b0ff }
    class func materialLightBlueA700() -> UIColor { return %+0x0091ea }
    class func materialLightBlue() -> UIColor { return materialLightBlue500() }

    class func materialCyan50() -> UIColor { return %+0xe0f7fa }
    class func materialCyan100() -> UIColor { return %+0xb2ebf2 }
    class func materialCyan200() -> UIColor { return %+0x80deea }
    class func materialCyan300() -> UIColor { return %+0x4dd0e1 }
    class func materialCyan400() -> UIColor { return %+0x26c6da }
    class func materialCyan500() -> UIColor { return %+0x00bcd4 }
    class func materialCyan600() -> UIColor { return %+0x00acc1 }
    class func materialCyan700() -> UIColor { return %+0x0097a7 }
    class func materialCyan800() -> UIColor { return %+0x00838f }
    class func materialCyan900() -> UIColor { return %+0x006064 }
    class func materialCyanA100() -> UIColor { return %+0x84ffff }
    class func materialCyanA200() -> UIColor { return %+0x18ffff }
    class func materialCyanA400() -> UIColor { return %+0x00e5ff }
    class func materialCyanA700() -> UIColor { return %+0x00b8d4 }
    class func materialCyan() -> UIColor { return materialCyan500() }

    class func materialTeal50() -> UIColor { return %+0xe0f2f1 }
    class func materialTeal100() -> UIColor { return %+0xb2dfdb }
    class func materialTeal200() -> UIColor { return %+0x80cbc4 }
    class func materialTeal300() -> UIColor { return %+0x4db6ac }
    class func materialTeal400() -> UIColor { return %+0x26a69a }
    class func materialTeal500() -> UIColor { return %+0x009688 }
    class func materialTeal600() -> UIColor { return %+0x00897b }
    class func materialTeal700() -> UIColor { return %+0x00796b }
    class func materialTeal800() -> UIColor { return %+0x00695c }
    class func materialTeal900() -> UIColor { return %+0x004d40 }
    class func materialTealA100() -> UIColor { return %+0xa7ffeb }
    class func materialTealA200() -> UIColor { return %+0x64ffda }
    class func materialTealA400() -> UIColor { return %+0x1de9b6 }
    class func materialTealA700() -> UIColor { return %+0x00bfa5 }
    class func materialTeal() -> UIColor { return materialTeal500() }

    class func materialGreen50() -> UIColor { return %+0xd0f8ce }
    class func materialGreen100() -> UIColor { return %+0xa3e9a4 }
    class func materialGreen200() -> UIColor { return %+0x72d572 }
    class func materialGreen300() -> UIColor { return %+0x42bd41 }
    class func materialGreen400() -> UIColor { return %+0x2baf2b }
    class func materialGreen500() -> UIColor { return %+0x259b24 }
    class func materialGreen600() -> UIColor { return %+0x0a8f08 }
    class func materialGreen700() -> UIColor { return %+0x0a7e07 }
    class func materialGreen800() -> UIColor { return %+0x056f00 }
    class func materialGreen900() -> UIColor { return %+0x0d5302 }
    class func materialGreenA100() -> UIColor { return %+0xa2f78d }
    class func materialGreenA200() -> UIColor { return %+0x5af158 }
    class func materialGreenA400() -> UIColor { return %+0x14e715 }
    class func materialGreenA700() -> UIColor { return %+0x12c700 }
    class func materialGreen() -> UIColor { return materialGreen500() }

    class func materialLightGreen50() -> UIColor { return %+0xf1f8e9 }
    class func materialLightGreen100() -> UIColor { return %+0xdcedc8 }
    class func materialLightGreen200() -> UIColor { return %+0xc5e1a5 }
    class func materialLightGreen300() -> UIColor { return %+0xaed581 }
    class func materialLightGreen400() -> UIColor { return %+0x9ccc65 }
    class func materialLightGreen500() -> UIColor { return %+0x8bc34a }
    class func materialLightGreen600() -> UIColor { return %+0x7cb342 }
    class func materialLightGreen700() -> UIColor { return %+0x689f38 }
    class func materialLightGreen800() -> UIColor { return %+0x558b2f }
    class func materialLightGreen900() -> UIColor { return %+0x33691e }
    class func materialLightGreenA100() -> UIColor { return %+0xccff90 }
    class func materialLightGreenA200() -> UIColor { return %+0xb2ff59 }
    class func materialLightGreenA400() -> UIColor { return %+0x76ff03 }
    class func materialLightGreenA700() -> UIColor { return %+0x64dd17 }
    class func materialLightGreen() -> UIColor { return materialLightGreen500() }

    class func materialLime50() -> UIColor { return %+0xf9fbe7 }
    class func materialLime100() -> UIColor { return %+0xf0f4c3 }
    class func materialLime200() -> UIColor { return %+0xe6ee9c }
    class func materialLime300() -> UIColor { return %+0xdce775 }
    class func materialLime400() -> UIColor { return %+0xd4e157 }
    class func materialLime500() -> UIColor { return %+0xcddc39 }
    class func materialLime600() -> UIColor { return %+0xc0ca33 }
    class func materialLime700() -> UIColor { return %+0xafb42b }
    class func materialLime800() -> UIColor { return %+0x9e9d24 }
    class func materialLime900() -> UIColor { return %+0x827717 }
    class func materialLimeA100() -> UIColor { return %+0xf4ff81 }
    class func materialLimeA200() -> UIColor { return %+0xeeff41 }
    class func materialLimeA400() -> UIColor { return %+0xc6ff00 }
    class func materialLimeA700() -> UIColor { return %+0xaeea00 }
    class func materialLime() -> UIColor { return materialLime500() }

    class func materialYellow50() -> UIColor { return %+0xfffde7 }
    class func materialYellow100() -> UIColor { return %+0xfff9c4 }
    class func materialYellow200() -> UIColor { return %+0xfff59d }
    class func materialYellow300() -> UIColor { return %+0xfff176 }
    class func materialYellow400() -> UIColor { return %+0xffee58 }
    class func materialYellow500() -> UIColor { return %+0xffeb3b }
    class func materialYellow600() -> UIColor { return %+0xfdd835 }
    class func materialYellow700() -> UIColor { return %+0xfbc02d }
    class func materialYellow800() -> UIColor { return %+0xf9a825 }
    class func materialYellow900() -> UIColor { return %+0xf57f17 }
    class func materialYellowA100() -> UIColor { return %+0xffff8d }
    class func materialYellowA200() -> UIColor { return %+0xffff00 }
    class func materialYellowA400() -> UIColor { return %+0xffea00 }
    class func materialYellowA700() -> UIColor { return %+0xffd600 }
    class func materialYellow() -> UIColor { return materialYellow500() }

    class func materialAmber50() -> UIColor { return %+0xfff8e1 }
    class func materialAmber100() -> UIColor { return %+0xffecb3 }
    class func materialAmber200() -> UIColor { return %+0xffe082 }
    class func materialAmber300() -> UIColor { return %+0xffd54f }
    class func materialAmber400() -> UIColor { return %+0xffca28 }
    class func materialAmber500() -> UIColor { return %+0xffc107 }
    class func materialAmber600() -> UIColor { return %+0xffb300 }
    class func materialAmber700() -> UIColor { return %+0xffa000 }
    class func materialAmber800() -> UIColor { return %+0xff8f00 }
    class func materialAmber900() -> UIColor { return %+0xff6f00 }
    class func materialAmberA100() -> UIColor { return %+0xffe57f }
    class func materialAmberA200() -> UIColor { return %+0xffd740 }
    class func materialAmberA400() -> UIColor { return %+0xffc400 }
    class func materialAmberA700() -> UIColor { return %+0xffab00 }
    class func materialAmber() -> UIColor { return materialAmber500() }

    class func materialOrange50() -> UIColor { return %+0xfff3e0 }
    class func materialOrange100() -> UIColor { return %+0xffe0b2 }
    class func materialOrange200() -> UIColor { return %+0xffcc80 }
    class func materialOrange300() -> UIColor { return %+0xffb74d }
    class func materialOrange400() -> UIColor { return %+0xffa726 }
    class func materialOrange500() -> UIColor { return %+0xff9800 }
    class func materialOrange600() -> UIColor { return %+0xfb8c00 }
    class func materialOrange700() -> UIColor { return %+0xf57c00 }
    class func materialOrange800() -> UIColor { return %+0xef6c00 }
    class func materialOrange900() -> UIColor { return %+0xe65100 }
    class func materialOrangeA100() -> UIColor { return %+0xffd180 }
    class func materialOrangeA200() -> UIColor { return %+0xffab40 }
    class func materialOrangeA400() -> UIColor { return %+0xff9100 }
    class func materialOrangeA700() -> UIColor { return %+0xff6d00 }
    class func materialOrange() -> UIColor { return materialOrange500() }

    class func materialDeepOrange50() -> UIColor { return %+0xfbe9e7 }
    class func materialDeepOrange100() -> UIColor { return %+0xffccbc }
    class func materialDeepOrange200() -> UIColor { return %+0xffab91 }
    class func materialDeepOrange300() -> UIColor { return %+0xff8a65 }
    class func materialDeepOrange400() -> UIColor { return %+0xff7043 }
    class func materialDeepOrange500() -> UIColor { return %+0xff5722 }
    class func materialDeepOrange600() -> UIColor { return %+0xf4511e }
    class func materialDeepOrange700() -> UIColor { return %+0xe64a19 }
    class func materialDeepOrange800() -> UIColor { return %+0xd84315 }
    class func materialDeepOrange900() -> UIColor { return %+0xbf360c }
    class func materialDeepOrangeA100() -> UIColor { return %+0xff9e80 }
    class func materialDeepOrangeA200() -> UIColor { return %+0xff6e40 }
    class func materialDeepOrangeA400() -> UIColor { return %+0xff3d00 }
    class func materialDeepOrangeA700() -> UIColor { return %+0xdd2c00 }
    class func materialDeepOrange() -> UIColor { return materialDeepOrange500() }

    class func materialBrown50() -> UIColor { return %+0xefebe9 }
    class func materialBrown100() -> UIColor { return %+0xd7ccc8 }
    class func materialBrown200() -> UIColor { return %+0xbcaaa4 }
    class func materialBrown300() -> UIColor { return %+0xa1887f }
    class func materialBrown400() -> UIColor { return %+0x8d6e63 }
    class func materialBrown500() -> UIColor { return %+0x795548 }
    class func materialBrown600() -> UIColor { return %+0x6d4c41 }
    class func materialBrown700() -> UIColor { return %+0x5d4037 }
    class func materialBrown800() -> UIColor { return %+0x4e342e }
    class func materialBrown900() -> UIColor { return %+0x3e2723 }
    class func materialBrown() -> UIColor { return materialBrown500() }

    class func materialGray50() -> UIColor { return %+0xfafafa }
    class func materialGray100() -> UIColor { return %+0xf5f5f5 }
    class func materialGray200() -> UIColor { return %+0xeeeeee }
    class func materialGray300() -> UIColor { return %+0xe0e0e0 }
    class func materialGray400() -> UIColor { return %+0xbdbdbd }
    class func materialGray500() -> UIColor { return %+0x9e9e9e }
    class func materialGray600() -> UIColor { return %+0x757575 }
    class func materialGray700() -> UIColor { return %+0x616161 }
    class func materialGray800() -> UIColor { return %+0x424242 }
    class func materialGray900() -> UIColor { return %+0x212121 }
    class func materialGray() -> UIColor { return materialGray500() }

    class func materialBlueGray50() -> UIColor { return %+0xeceff1 }
    class func materialBlueGray100() -> UIColor { return %+0xcfd8dc }
    class func materialBlueGray200() -> UIColor { return %+0xb0bec5 }
    class func materialBlueGray300() -> UIColor { return %+0x90a4ae }
    class func materialBlueGray400() -> UIColor { return %+0x78909c }
    class func materialBlueGray500() -> UIColor { return %+0x607d8b }
    class func materialBlueGray600() -> UIColor { return %+0x546e7a }
    class func materialBlueGray700() -> UIColor { return %+0x455a64 }
    class func materialBlueGray800() -> UIColor { return %+0x37474f }
    class func materialBlueGray900() -> UIColor { return %+0x263238 }
    class func materialBlueGray() -> UIColor { return materialBlueGray500() }

}